In [14]:
# Imports
import pandas as pd

In [13]:
#First of all, load the csv brain data with the significant variables
data = pd.read_csv("BrainMatrixData.csv") 
data.head()

,Column1,Column2,Column3,Column4,Column5,Column6,Column7,Column8,Column9,Column10,...,Column376,Column377,Column378,Column379,Column380,Column381,Column382,Column383,Column384,Column385
0,19.783990,19.314470,19.142825,19.185161,13.499028,17.694012,8.756266,19.141286,19.187837,14.834598,...,3.618421,3.223684,4.000000,4.013158,3.065789,4.736842,4.605263,4.605263,5.578947,ms
1,16.733469,12.910102,11.812794,17.734108,11.060022,11.744588,7.687872,19.032041,14.390918,10.717530,...,4.197368,5.236842,4.552632,4.736842,3.855263,4.342105,4.526316,4.447368,5.500000,ms
2,18.424258,15.705767,16.174190,19.745516,15.631004,12.928705,9.509393,20.030737,17.674618,13.425871,...,3.644737,3.631579,4.000000,3.973684,3.078947,3.605263,5.065789,4.644737,6.039474,ms
3,19.591100,22.772947,11.736065,19.648423,14.513728,15.147721,5.711180,21.832772,20.116815,14.765563,...,4.197368,4.407895,4.065789,4.039474,3.144737,4.460526,4.894737,4.565789,5.868421,ms
4,18.533265,15.463072,12.038137,16.380761,14.586402,15.148913,11.773108,16.310207,18.340773,14.913160,...,3.276316,2.736842,4.039474,4.000000,3.105263,3.842105,4.460526,4.618421,5.434211,ms